version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./src/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS (SSL 인증서 적용 시 사용)
    depends_on:
      - springboot
      - redis
      - grafana
      - prometheus

  springboot:
    image: my-spring-app
    container_name: springboot
    build:
      context: ./src/user
      dockerfile: Dockerfile
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://localhost:3306/bookcalendar
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    expose:
      - "8080" # 내부 통신용

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - ./src/redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - "6379"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./src/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    expose:
      - "9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    volumes:
      - ./src/monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini
    expose:
      - "3000"
