FROM eclipse-temurin:17-jdk-alpine

# 컨테이너 안의 작업 디렉토리 : /app
WORKDIR /app

# 로컬 머신의 build/libs/ 디렉토리에서 .jar 파일을 찾아 /app/app.jar로 복사
# 일반적으로 Spring Boot에서 ./gradlew build 하면 build/libs/에 .jar가 생성됨
COPY build/libs/*.jar app.jar

# 컨테이너에서 사용하는 포트를 외부에 열어줌 (문서용)
EXPOSE 8080

# 컨테이너가 시작되면 실행할 명령어
# java -jar /app/app.jar → Spring Boot 앱 실행
ENTRYPOINT ["java","-jar","/app/app.jar"] 